### ISSUE TITLE
including Mutex_m in a class doesn't initialise @_mutex

### ISSUE THREAD

**Issue by feyeleanor** [ruby/mutex_m#1]
Extending an object does work, including the module currently doesn't but the documentation says it does.

Hooking the included callback will fix this.

**Comment by znz** [comment]
`include Mutex_m` requires calling `super` in `initialize` if you write own `initialize`.
https://github.com/ruby/mutex_m/blob/4a983cecff958cb704e0639d67e5b5acb92d4bc9/lib/mutex_m.rb#L108-L111

So I think it is documentation problem.

**Comment by feyeleanor** [comment]
This worked back in Ruby 1.8 without needing mu_initialize to be called. I discovered this when playing with some of my old code from 2008 that worked at that time but doesn't work now without modification (I chose to use Extend instead as it's easier on my eyes).
